### ISSUE TITLE
View Case History

### ISSUE THREAD

**Issue by escapehatch14** [Kvoti/ditto#41]
In View Case History on a user’s profile page, the text of that case note is not aligned properly? 
  Seems to be indented (like this :).

**Comment by mallison** [comment]
Eh, not sure what you mean. Can you attach a screen shot? I don't think I've bootstrapified the markup there so may not look quite right.

**Comment by escapehatch14** [comment]
https://www.dropbox.com/s/o0hrdd44tt13obk/Screenshot%202015-11-10%2015.31.14.png?dl=0

**Comment by mallison** [comment]
Thanks, I see now! I'd not tested with long case not titles.

**Comment by escapehatch14** [comment]
Good. I've got to go out now up to town, but I'll catch up again tomorrow
morn, ya?

Sarah Dyer-Hall

M | 07590 385 639
T | 020 8333 8473
@DesignGenius
