### ISSUE TITLE
Hierarchy: stacking of chat and sessions

### ISSUE THREAD

**Issue by escapehatch14** [Kvoti/ditto#43]
We need to think about how we display multiple sessions with the same user. I’ve created several session now with ‘different’ users and a double session with the ‘same’ user. They all display under the same stack. I think they should be clustered together? Try it for yourself and see. I’ll send you a screenshot.

**Comment by escapehatch14** [comment]
https://www.dropbox.com/s/zr6lsyhlflzdkv8/Screenshot%202015-11-10%2015.28.38.png?dl=0

**Comment by escapehatch14** [comment]
Bloody screenshot disappeared so I've just DB'ed it.

**Comment by mallison** [comment]
Not sure what you mean again :/ The thread list is, currently, in reverse date order. So depending on when messages were sent sessions/chats between the same two users won't necessarily show together.

**Comment by escapehatch14** [comment]
OK, so think What's App. Each message (or chat/session in this case) is stored 'under each person's name', so say, if 'member 1' has two chats, both will appear under 'member 1'. At the moment, you see two entries as it were for 'member 1'.

**Comment by mallison** [comment]
WhatsApp doesn't have multiple chats per person -- there's just a single thread.

But if you want to group threads together we could do that.

Maybe easier if you did a quick sketch/mockup of what you have in mind?
