### ISSUE TITLE
Comments on Case Notes

### ISSUE THREAD

**Issue by escapehatch14** [Kvoti/ditto#45]
When you try and leave a comment on a Case Note, you get the [object, object] thing again and can't input.

**Comment by escapehatch14** [comment]
Also, the comment field below displays goobledegook, see screenshot.
![screenshot 2015-11-11 11 31 43](https://cloud.githubusercontent.com/assets/8806601/11090206/eade14a0-8867-11e5-973f-68e8758a18c3.png)

**Comment by mallison** [comment]
Oh dear! This must be another input that's using the old validation stuff. I'll update.
